# -*- coding: utf-8 -*-
"""proje (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RzRx5FQtrl8TJojSo0z0gW7xEDtzM01i
"""

import random #BİLGİSAYARA SEÇİM YAPTIRMAK İÇİN RANDOM KÜTÜPHANESİ KULLANILDI
import sys #SİSTEMDEN SYS.EXİT İLE ÇIKIŞ YAPABİLMEK İÇİN SYS KÜTÜPHANESİ KULLANILDI

def tas_kagit_makas_YASEMIN_TURKOGLU():
 sayaç = 0
 oyuncu_kazandi = 0
 bilgisayar_kazandi = 0

 global seçimler

 seçimler = ["taş","kağıt","makas"]
 evethayir = ["evet","hayır"]

#OYUNCUNUN OYNAMA SIRASI
 def oyuncu_secimi():


    print("Taş - kağıt - makas 'tan birini seçiniz.")
    global seçim1
    seçim1 = input()
    seçim1=seçim1.lower() #SEÇİMİ KÜÇÜK HARFE DÖNÜŞTÜRÜR.


    print(f"{seçim1} 'ı seçtiniz.")

    oyun()
    oyuncu_secimi()

#SİSTEMİ KAPATAN FONKSİYON
 def kapanis():
  print("Hoşçakalın")
  print("Yeniden oynamak istiyor musunuz? E/H")
  yanit=input()
  yanit=yanit.lower()
  if yanit=="e":
    giris0()
  elif yanit=="h":
    print("Hoşçakalın! Yine beklerim! ;)")
    sys.exit()
  else:
    print("Yanlış giriş yaptınız.Boşuna elektrik harcamasan mı?")
    sys.exit()

#OYUN BİTTİĞİNDE TURLARI SIFIRLAR VE OYUNDAN ÇIKAR
 def cikis():

  print("Oyundan çıktınız.")
  tur_sıfırla()
  oyuncu_sıfırla()
  bilgisayar_sıfırla()

  kapanis()

#OYUNUN KURALLARI
 def giris0():

   print("Taş, kağıt, makas oyunu hakkında bilgilendirme istiyor musunuz?")
   global cevap
   cevap=input("E/H?  ")
   cevap=cevap.upper() #SEÇİMİ BÜYÜK HARFE DÖNÜŞTÜRÜR
   if (cevap=="E"):
    print("""Oyun hakkında bilgi: Taş-kağıt-makas oyunu, iki oyuncunun sırayla seçtiği bir simgeyle oynanan basit bir oyundur.
     Taş, makası kırar; makas, kağıdı keser; kağıt, taşı kaplar.
          Her oyuncu bir simge seçer ve karşılaştırma yapılır.
          Kazanan, kurallara göre belirlenir.
          Oyunun temel amacı şansa dayalı bir rekabet sunmaktır.
          Taraflardan biri 2 kez kazanınca oyun biter!""")
    giris1()
    oyun()


   elif (cevap=="H"):
     giris1()
     print("Eğer bilgisayar da isterse oyuna başlamaya hazırsınız!")
     oyun()
   else:
    print("Yanlış giriş yaptınız.")
    giris0()

#OYUNCUYA OYUN OYNAMAK İSTEYİP İSTEMEDİĞİ SORUSU
 def giris1():
  global cevap1
  cevap1=input("Oyun oynamak istiyor musunuz? E/H?  ")
  cevap1=cevap1.upper()
  if (cevap1=="E"):
    print("Eğer bilgisayar da isterse oyun başlasın:")
    oyunbaslama()
  elif (cevap1=="H"):
    kapanis()

  else:
     print("Yanlış giriş yaptınız.")
     giris1()

#BİLGİSAYARIN OYUNA BAŞLAMAK İSTEME VE İSTEMEME KOŞULU
 def oyunbaslama():
  global oyun_secimi
  oyun_secimi = random.choice(evethayir)

  if (cevap1== "E") or (cevap== "H"):
    if (oyun_secimi== "evet"):
      print("""Ben de oynamak istiyorum!
     Her iki taraf da oyun oynamaya hazır olduğuna göre oyun başlasın!""")
      oyuncu_secimi()

      oyun()

    elif (oyun_secimi== "hayır"):
      print("""Üzgünüm, bilgisayar oyun oynamak istemiyor.
     Kendine bir insan bulmaya ne dersin?""")
      cikis()

  else:
    print("Boşuna elektrik tüketmemeye ne dersin dostum!?")
    cikis()

    #TURLARI SAYAR
 def tur_say():
   global sayaç
   sayaç += 1
   print(f"{sayaç}.tur tamamlandı!")

   #OYUN BİTTİĞİNDE TURU SIFIRLAR
 def tur_sıfırla():
  global sayaç
  sayaç = 0

   #OYUNCUNUN KAZANDIĞI OYUNLARI SAYAR
 def kazanan_oyuncu():
  global oyuncu_kazandi
  oyuncu_kazandi += 1
  print(f"Skorunuz: {oyuncu_kazandi}")

  #OYUN BİTTİĞİNDE OYUNCUNUN SKORUNU SIFIRLAR
 def oyuncu_sıfırla():
  global oyuncu_kazandi
  oyuncu_kazandi=0

 #BİLGİSAYAR KAZANDI
 def kazanan_bilgisayar():
  global bilgisayar_kazandi
  bilgisayar_kazandi += 1
  print(f"Skorum: {bilgisayar_kazandi}")

 #OYUN BİTTİĞİNDE BİLGİSAYARIN SKORUNU SIFIRLAR

 def bilgisayar_sıfırla():
  global bilgisayar_kazandi
  bilgisayar_kazandi = 0

#TAŞ - KAĞIT - MAKAS OYUNU
 def oyun():
  global oyuncu_kazandi
  global bilgisayar_kazandi
  global bilgisayarin_secimi
  bilgisayarin_secimi = random.choice(seçimler)
  print(f" Ben {bilgisayarin_secimi} seçtim.")

  while (oyuncu_kazandi <= 2) and (bilgisayar_kazandi <= 2):

   if (seçim1=="taş") and (bilgisayarin_secimi=="makas"): #Taş, makası kırar; makas, kağıdı keser; kağıt, taşı kaplar.
    tur_say()
    kazanan_oyuncu()

    print("Kazandınız! Taş, makası kırar!")

    while (oyuncu_kazandi==2) or (bilgisayar_kazandi==2):
     print(f"""Oyun bitti.
    SKOR: Siz:{oyuncu_kazandi} & Ben: {bilgisayar_kazandi}""")
     cikis()
     break

    oyuncu_secimi()


   elif (seçim1=="makas") and (bilgisayarin_secimi=="taş"):

     tur_say()
     kazanan_bilgisayar()

     print("Ben kazandım. Taş, makası kırar!")

     while (oyuncu_kazandi==2) or (bilgisayar_kazandi==2):
      print(f"""Oyun bitti.
    SKOR: Siz:{oyuncu_kazandi} & Ben: {bilgisayar_kazandi}""")
      cikis()
      break
     oyuncu_secimi()


   elif (seçim1=="makas") and (bilgisayarin_secimi=="kağıt"):

     tur_say()
     kazanan_oyuncu()
     bilgisayar_kazandi
     print("Kazandınız! Makas, kağıdı keser!")

     while (oyuncu_kazandi==2) or (bilgisayar_kazandi==2):
      print(f"""Oyun bitti.
    SKOR: Siz:{oyuncu_kazandi} & Ben: {bilgisayar_kazandi}""")
      cikis()
      break
     oyuncu_secimi()

   elif (seçim1=="kağıt") and (bilgisayarin_secimi=="makas"):

     tur_say()
     kazanan_bilgisayar()

     print("Ben kazandım. Makas, kağıdı keser!")

     while (oyuncu_kazandi==2) or (bilgisayar_kazandi==2):
      print(f"""Oyun bitti.
    SKOR: Siz:{oyuncu_kazandi} & Ben: {bilgisayar_kazandi}""")
      cikis()
      break
     oyuncu_secimi()

   elif (seçim1=="kağıt") and (bilgisayarin_secimi=="taş"):

     tur_say()
     kazanan_oyuncu()

     print("Kazandınız! Kağıt, taşı kaplar!")

     while (oyuncu_kazandi==2) or (bilgisayar_kazandi==2):
      print(f"""Oyun bitti.
    SKOR: Siz:{oyuncu_kazandi} & Ben: {bilgisayar_kazandi}""")
      cikis()
      break

     oyuncu_secimi()

   elif (seçim1=="taş") and (bilgisayarin_secimi=="kağıt"):


     tur_say()
     kazanan_bilgisayar()

     print("Ben kazandım. Kağıt, taşı kaplar!")

     while (oyuncu_kazandi==2) or (bilgisayar_kazandi==2):
      print(f"""Oyun bitti.
    SKOR: Siz:{oyuncu_kazandi} & Ben: {bilgisayar_kazandi}""")


      cikis()
      break

     oyuncu_secimi()

   elif (seçim1==bilgisayarin_secimi):

     tur_say()
     print("Berabere! Yeniden deneyin:")
     oyuncu_secimi()


 giris0()
tas_kagit_makas_YASEMIN_TURKOGLU()